# Generated by Django 5.2.11 on 2026-02-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VidandFace', '0002_capturerating_user_uservideoprogress_watchedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturerating',
            name='arousal',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='capturerating',
            name='valence',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
